### ISSUE TITLE
failed to load bundle

### ISSUE THREAD

**Issue by wangjianpeng** [arkntools/unity-js#3]
I can load my bundle by *AssetBundle.LoadFromFile* in c#, but failed to load the same bundle by this package, the error is 
```
/home/gitprojects/unity-js/unity-js/dist/bundle.js:222
            throw new Error(`Unsupported compression type: ${type}`);
                  ^

Error: Unsupported compression type: 1
    at decompressBuffer (/home/gitprojects/unity-js/unity-js/dist/bundle.js:222:19)
    at Bundle.readBlocks (/home/gitprojects/unity-js/unity-js/dist/bundle.js:188:40)
    at new Bundle (/home/gitprojects/unity-js/unity-js/dist/bundle.js:89:56)
    at load (/home/gitprojects/unity-js/unity-js/dist/bundle.js:64:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/gitprojects/unity-js/unity-js/mydemo/mybundle.js:5:20
````
could you find the reason ?

**Comment by Tsuk1ko** [comment]
As this package is only for supporting the games I need, there are many functions that have not been implemented yet.

For example, your AssetBundle here uses LZMA compression (compression type is `1`).

At present, this library only supports LZ4 decompression. Maybe I will consider implement it in the future.

**Comment by Tsuk1ko** [comment]
Are you willing to provide the AssetBundle so that I can test it?

**Comment by wangjianpeng** [comment]
I use code with `BuildAssetBundleOptions.None` without LZMA .
I review code, it will create json file to scriptable asset , create atlas from image , then build them to bundle together.
I upload the bundle file and source file .
[bundle_and_source.zip](https://github.com/user-attachments/files/15803378/bundle_and_source.zip)
hope you can test them.

**Comment by Tsuk1ko** [comment]
Well but its data blocks do use LZMA compression.

I have added LZMA support, now it can be read.

![image](https://github.com/arkntools/unity-js/assets/24877906/cc000453-44be-4faf-b1d5-b8c980c6dd6b)

```
bunldes/english AssetBundle
icon_successfully Sprite
atlas SpriteAtlas
sactx-256x256-ETC2-atlas-a06c78d3 Texture2D
```

**Comment by wangjianpeng** [comment]
Great, thank you your to fix it.
actually , each bundle contains `language` asset data which is custom ScriptableObject. how can I get language data , or  is there guide to allow me load similar ScriptableObject asset by myself ?
![image](https://github.com/arkntools/unity-js/assets/4220174/410f10b6-9f7f-434f-acf8-e29a27ccd82a)

**Comment by Tsuk1ko** [comment]
Currently I have no plan to support other type of asset objects.

This project is mainly for my own use, so I only implement what I need. Although it is not hard, it is a boring job and will take a lot of time.

So I suggest you use the tools or libraries mentioned at the end of README, which support exporting what you want.
